# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecolor < Formula
  desc "Colorize your kubectl output"
  homepage "https://github.com/smiller171/kubecolor"
  version "0.0.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smiller171/kubecolor/releases/download/v0.0.23/kubecolor_0.0.23_Darwin_x86_64.tar.gz"
      sha256 "310c87e9320879c0d6f2c80f26b6e7240f3c8371732cd13d734cea9214f98c91"

      def install
        bin.install "kubecolor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smiller171/kubecolor/releases/download/v0.0.23/kubecolor_0.0.23_Darwin_arm64.tar.gz"
      sha256 "3f464ef1f4d46e7b28c1d297edaad9b8779e1ae67edcb53ead448e2e1ae46fa4"

      def install
        bin.install "kubecolor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smiller171/kubecolor/releases/download/v0.0.23/kubecolor_0.0.23_Linux_arm64.tar.gz"
      sha256 "81d6841c0242615ec79d76e1231d5a8873d375aed3026a9efa81c758020ffcd7"

      def install
        bin.install "kubecolor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/smiller171/kubecolor/releases/download/v0.0.23/kubecolor_0.0.23_Linux_x86_64.tar.gz"
      sha256 "f396c66b524acd6bc35731910eeb8fa23a4baab29e20ef27e3e2f8a099f8e3a0"

      def install
        bin.install "kubecolor"
      end
    end
  end
end
